### ISSUE TITLE
ENOENT: no such file or directory, stat '/views/index.html'

### ISSUE THREAD

**Issue by ghost** [ohomer/koa-nunjucks-render#2]
app.js
`
import Koa              from 'koa';
import convert          from 'koa-convert';
import nunjucksRender   from 'koa-nunjucks-render';
import nunjucks         from 'nunjucks';
import path             from 'path';
import serve            from 'koa-static';
import views            from 'koa-views';
// 路由
import homeRouter from './routers/home.router.js';

const app = new Koa();
const nunjucksOptions = {
  ext: '.html',
  noCache: process.env.NODE_ENV === 'development',
  watch:true
}

app.use(convert(nunjucksRender('views', nunjucksOptions)));
// Must be used before any router is used
// app.use(views(__dirname + 'views', {
//   map: {
//     html: 'nunjucks'
//   }
// }));
app.use(async (ctx)=>{
  await ctx.render('./index');
})

app.listen(3000, () => {
  console.log('Listening on port', 3000);
})

`
after i build app.js with webpack     koa-nunjucks-render cannot fount the template index.html

my file structure 👍 
build:
  app.js
  index.html
 views
     index.html

**Comment by ghost** [comment]
➜  koa-in-action git:(master) ✗ DEBUG=koa* node build/app.js
  koa-router defined route HEAD,GET / +0ms
  koa:application use converted +5ms
  koa:application use - +1ms
  koa:application listen +0ms
Listening on port 3000

  Error: template not found: index.html
      at createTemplate (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/environment.js:206:31)
      at next (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/lib.js:210:13)
      at handle (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/environment.js:252:25)
      at /Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/environment.js:263:21
      at next (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/lib.js:207:13)
      at Object.exports.asyncIter (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/lib.js:214:5)
      at new_cls.getTemplate (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/environment.js:242:17)
      at new_cls.render (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/src/environment.js:304:14)
      at Object.module.exports.render (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/node_modules/nunjucks/index.js:72:14)
      at /Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/index.js:26:18
      at Object.render (/Users/admin/code_repositories/git/Coding/koa-in-action/node_modules/koa-nunjucks-render/index.js:25:14)
      at /Users/admin/code_repositories/git/Coding/koa-in-action/build/app.js:97:16
      at next (native)
      at step (/Users/admin/code_repositories/git/Coding/koa-in-action/build/app.js:83:192)
      at /Users/admin/code_repositories/git/Coding/koa-in-action/build/app.js:83:438
      at /Users/admin/code_repositories/git/Coding/koa-in-action/build/app.js:83:100

**Comment by ghost** [comment]
oh
   view path base of current process.cwd()
